server.port=8080

meta.whatsapp.token=EAAVa9iZCSlgEBRWBrrtZAFcYSUZBve2LTYTDN4LZA9B0x9lzVZC77i2GGRaZBcWo5hZBowsVvs5cuyJC68EZBwfRfp6lc1cWEsUHD79ARutkVw2VSfzrLegD4hga8ZAvvgd0WJ1bCZBCm4wvwHt9Oa9d0KYhOZBvDgK7Jb1VT3lKZACv8HekO2NvLfUFRtKWc1FiuBeZC7y1OmDWgpNzNtzBLEWO1qxgIYHkqdXYOZBGyInKCTj64BQZAlvMaqzZC8ix1T6F2LHBfhCCHPEEESt3vykXJgZCknWOB
meta.whatsapp.phone-number-id=996050323601040
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=contactobasados@gmail.com
spring.mail.password=sljvwkhkstrxsljz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true