server.port=8080

meta.whatsapp.token=EAAVa9iZCSlgEBRTWG4BfXgV6ZCdc1OIKF7Tbo5hsCe81ZBME7UhdtHdecKHhyH6PRcAL2subNk5lcHt1foTy7smZADZCqj705yFkwQ28zlLTKFKddOcs1ZA7IZCzbYmm9ACbMyBp0jZBtRcBFg8I2GZAOflzsRHL74dxZBF40YhOfBG2rZC0ZAVNFT6VXcZCvA9PrZBJoNBJZBmmJYowOvJRVZCC4KjObVeX0ETrM1FnYbQPZA3ktc1K68io6G7BcMVR8291u2i4Q9pbsJTyNLVhbZBmOICpZBn5zNyPQZDZD
meta.whatsapp.phone-number-id=996050323601040

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=contactobasados@gmail.com
spring.mail.password=dsrzhgnoanszygsc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000